# Generated by Django 5.0.1 on 2025-12-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Venue name (e.g., 'Waltham Public Library')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly venue identifier', max_length=200)),
                ('street_address', models.CharField(blank=True, help_text="Street address (e.g., '735 Main Street')", max_length=255)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(help_text='State/region (abbreviation or full name)', max_length=50)),
                ('postal_code', models.CharField(blank=True, help_text='ZIP/postal code', max_length=20)),
                ('country', models.CharField(default='US', help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('source_domain', models.CharField(blank=True, help_text='Domain where venue was discovered', max_length=255)),
                ('canonical_url', models.URLField(blank=True, help_text="Venue's official website")),
                ('raw_schema', models.JSONField(blank=True, help_text='Original Schema.org Place data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug', 'city', 'state', 'postal_code'], name='venues_venu_slug_7fb6d8_idx'), models.Index(fields=['city', 'state'], name='venues_venu_city_e9a0b9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('slug', 'city', 'state', 'postal_code'), name='unique_venue_identity'),
        ),
    ]
