# Generated by Django 5.0.1 on 2025-12-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_add_lat_lng_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venue',
            name='venue_lat_lng_idx',
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='venue_lat_idx',
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='venue_lng_idx',
        ),
    ]
