# Generated by Django 5.0.1 on 2026-01-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_remove_redundant_lat_lng_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='audience_age_groups',
            field=models.JSONField(blank=True, default=list, help_text='Age groups: infant, toddler, child, teen, adult, senior'),
        ),
        migrations.AddField(
            model_name='venue',
            name='audience_min_age',
            field=models.IntegerField(blank=True, help_text='Minimum recommended age', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='audience_primary',
            field=models.CharField(choices=[('children', 'Children'), ('dogs', 'Dogs'), ('senior', 'Senior'), ('general', 'General')], default='general', help_text='Primary audience', max_length=16),
        ),
        migrations.AddField(
            model_name='venue',
            name='audience_tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags: families, dogs, stroller_friendly, wheelchair_accessible, etc.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, help_text='General venue description for RAG'),
        ),
        migrations.AddField(
            model_name='venue',
            name='enrichment_status',
            field=models.CharField(choices=[('none', 'Not Enriched'), ('partial', 'Partially Enriched'), ('complete', 'Fully Enriched')], default='none', help_text='Enrichment status', max_length=16),
        ),
        migrations.AddField(
            model_name='venue',
            name='kids_summary',
            field=models.TextField(blank=True, help_text='Kid-focused venue summary for RAG'),
        ),
        migrations.AddField(
            model_name='venue',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, help_text='When venue was last enriched', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_kind',
            field=models.CharField(blank=True, choices=[('library', 'Library'), ('museum', 'Museum'), ('park', 'Park'), ('playground', 'Playground'), ('beach', 'Beach'), ('skating_rink', 'Skating Rink'), ('dog_park', 'Dog Park'), ('pool', 'Pool'), ('school', 'School'), ('community_center', 'Community Center'), ('church', 'Church'), ('theater', 'Theater'), ('restaurant', 'Restaurant'), ('senior_center', 'Senior Center'), ('ymca', 'YMCA'), ('sports_facility', 'Sports Facility'), ('nature_center', 'Nature Center'), ('zoo', 'Zoo'), ('aquarium', 'Aquarium'), ('other', 'Other'), ('unknown', 'Unknown')], help_text='Type of venue', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_kind_confidence',
            field=models.FloatField(blank=True, help_text='Confidence in venue_kind classification (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_name_quality',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('address_only', 'Address Only'), ('empty', 'Empty'), ('placeholder', 'Placeholder'), ('unknown', 'Unknown')], help_text='Quality of venue name', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='website_url',
            field=models.URLField(blank=True, help_text="Venue's official website URL", null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='website_url_confidence',
            field=models.FloatField(blank=True, help_text='Confidence in website_url (0-1)', null=True),
        ),
        migrations.CreateModel(
            name='VenueHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='True if venue is closed this day')),
                ('notes', models.TextField(blank=True, help_text="Additional info (e.g., 'Closed 12-1pm for lunch')")),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Venue Hours',
                'verbose_name_plural': 'Venue Hours',
                'ordering': ['day_of_week'],
                'unique_together': {('venue', 'day_of_week')},
            },
        ),
    ]
