# Generated by Django 5.0.1 on 2026-01-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_add_venue_enrichment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='audience_primary',
            field=models.CharField(choices=[('general', 'General'), ('families', 'Families'), ('children', 'Children'), ('teens', 'Teens'), ('adults', 'Adults'), ('seniors', 'Seniors')], default='general', help_text='Primary audience', max_length=16),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_kind',
            field=models.CharField(blank=True, choices=[('library', 'Library'), ('museum', 'Museum'), ('park', 'Park'), ('playground', 'Playground'), ('beach', 'Beach'), ('skating_rink', 'Skating Rink'), ('dog_park', 'Dog Park'), ('pool', 'Pool'), ('school', 'School'), ('community_center', 'Community Center'), ('church', 'Church'), ('theater', 'Theater'), ('restaurant', 'Restaurant'), ('senior_center', 'Senior Center'), ('ymca', 'YMCA'), ('sports_facility', 'Sports Facility'), ('nature_center', 'Nature Center'), ('zoo', 'Zoo'), ('aquarium', 'Aquarium'), ('town_hall', 'Town Hall'), ('city_hall', 'City Hall'), ('government_office', 'Government Office'), ('other', 'Other'), ('unknown', 'Unknown')], help_text='Type of venue', max_length=32, null=True),
        ),
    ]
