# Generated by Django 5.0.1 on 2026-01-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_add_civic_venue_kinds'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city', 'state', 'street_address'], name='venue_address_lookup'),
        ),
    ]
