# Generated by Django 5.0.1 on 2026-01-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_add_address_lookup_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.CharField(blank=True, help_text='Raw category from OSM (library, museum, park, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='data_source',
            field=models.CharField(default='scraped', help_text="Data source: 'osm', 'scraped', or 'manual'", max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_hours_raw',
            field=models.TextField(blank=True, help_text='Operating hours in OSM format'),
        ),
        migrations.AddField(
            model_name='venue',
            name='operator',
            field=models.CharField(blank=True, help_text="Operating organization (e.g., 'Town of Needham')", max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='osm_id',
            field=models.BigIntegerField(blank=True, help_text='OpenStreetMap element ID', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='osm_type',
            field=models.CharField(blank=True, help_text='OSM element type: node, way, or relation', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='wikidata_id',
            field=models.CharField(blank=True, help_text='Wikidata ID for linked data enrichment', max_length=50),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['osm_type', 'osm_id'], name='venues_venu_osm_typ_7987a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(condition=models.Q(('osm_id__isnull', False)), fields=('osm_type', 'osm_id'), name='unique_osm_venue'),
        ),
    ]
