# Generated by Django 5.0.1 on 2026-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_add_osm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='events_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of event calendar URLs for this venue'),
        ),
    ]
