# Generated by Django 5.0.1 on 2026-01-14 22:12

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_venue_first_refactor_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='RAG vector embedding for venue semantic search', null=True),
        ),
    ]
