# Generated by Django 5.0.1 on 2026-01-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_add_venue_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Venue's official website", null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(blank=True, help_text='Raw category from OSM (library, museum, park, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='opening_hours_raw',
            field=models.TextField(blank=True, help_text='Operating hours in OSM format', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='operator',
            field=models.CharField(blank=True, help_text="Operating organization (e.g., 'Town of Needham')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP/postal code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='source_domain',
            field=models.CharField(blank=True, help_text='Domain where venue was discovered', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, help_text='State/region (abbreviation or full name)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='street_address',
            field=models.CharField(blank=True, help_text="Street address (e.g., '735 Main Street')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='wikidata_id',
            field=models.CharField(blank=True, help_text='Wikidata ID for linked data enrichment', max_length=50, null=True),
        ),
    ]
