# Generated by Django 5.0.1 on 2025-08-07 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_servicetoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="search_query",
        ),
        migrations.AddField(
            model_name="source",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_submissions",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="search_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual scrape"),
                    ("llm", "LLM search"),
                    ("calendar", "Calendar file"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                related_query_name="source_event",
                to="events.source",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
