# Generated by Django 5.0.1 on 2025-08-08 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_source_search_query_source_event_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="last_crawl",
            new_name="last_run_at",
        ),
        migrations.AddField(
            model_name="source",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="source",
            name="last_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_run", "Not run"),
                    ("in_progress", "In Progress"),
                    ("processed", "Processed"),
                ],
                default="not_run",
                max_length=20,
            ),
        ),
    ]
