# Generated by Django 5.0.1 on 2025-08-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_source_run_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="metadata_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
