# Generated by Django 5.0.1 on 2025-08-19 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_metadata_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=200, unique=True)),
                ("best_selectors", models.JSONField(blank=True, default=list)),
                ("pagination_pattern", models.CharField(blank=True, max_length=500)),
                ("cancellation_indicators", models.JSONField(blank=True, default=list)),
                ("success_rate", models.FloatField(default=0.0)),
                ("total_attempts", models.PositiveIntegerField(default=0)),
                ("successful_attempts", models.PositiveIntegerField(default=0)),
                ("last_successful", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="affiliate_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="affiliate_tracking_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="event",
            name="commission_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="revenue_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("domain", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("strategy_used", models.CharField(blank=True, max_length=100)),
                ("events_found", models.PositiveIntegerField(default=0)),
                ("pages_processed", models.PositiveIntegerField(default=1)),
                ("processing_time", models.FloatField(null=True)),
                ("error_message", models.TextField(blank=True)),
                ("lambda_request_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrapeBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jobs",
                    models.ManyToManyField(
                        related_name="batches", to="events.scrapingjob"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="scraping_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.scrapingjob",
            ),
        ),
    ]
