# Generated by Django 5.0.1 on 2025-08-19 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_sitestrategy_event_affiliate_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="site_strategy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="events.sitestrategy",
            ),
        ),
    ]
