# Generated by Django 5.0.1 on 2025-08-24 02:00

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_source_site_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
