# Generated by Django 5.0.1 on 2025-08-29 16:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_enable_pgvector_extension'),
    ]

    operations = [
        # Enable pg_trgm extension for trigram GIN indexes
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='desc_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
