# Generated by Django 5.0.1 on 2025-08-31 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_desc_gin_idx_event_embed_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_attendance_mode',
            field=models.CharField(blank=True, help_text='offline/online/mixed from Schema.org', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(blank=True, help_text='scheduled/cancelled/postponed from Schema.org', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, help_text='Event organizer name from Schema.org', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Fallback location string for backward compatibility', max_length=255),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Venue/room name (e.g., 'Children's Room')", max_length=200)),
                ('address', models.TextField(blank=True, help_text='Full address for geocoding and location searches')),
                ('telephone', models.CharField(blank=True, help_text='Contact phone number', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^[\\+]?[1-9]?[\\d\\s\\-\\(\\)\\.]+$')])),
                ('url', models.URLField(blank=True, help_text='Venue website')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for mapping', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for mapping', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='events_plac_name_a1961b_idx'), models.Index(fields=['address'], name='events_plac_address_01ff6d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(condition=models.Q(('address__isnull', False), models.Q(('address', ''), _negated=True)), fields=('address',), name='unique_venue_address'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Rich Schema.org Place object with full venue details', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.place'),
        ),
    ]
