# Generated by Django 5.0.1 on 2025-12-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_schema_org_place_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='extraction_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='locked_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_jobs', to='events.source'),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='worker_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='events_scra_status_98364e_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapingjob',
            index=models.Index(fields=['locked_at'], name='events_scra_locked__b3f48e_idx'),
        ),
    ]
