# Generated by Django 5.0.1 on 2025-12-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_add_job_queue_fields'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='raw_location_data',
            field=models.JSONField(blank=True, help_text='Full location_data from collector for debugging', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='raw_place_json',
            field=models.JSONField(blank=True, help_text='Original Schema.org Place JSON-LD for re-parsing', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='room_name',
            field=models.CharField(blank=True, help_text="Room/space within venue (e.g., 'Children's Room')", max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Structured venue with normalized address components', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.venue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text="Raw location string from collector (e.g., 'Waltham Room')", max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Legacy Schema.org Place object (kept for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.place'),
        ),
    ]
