# Generated by Django 5.0.1 on 2025-12-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_raw_location_data_event_raw_place_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
