# Generated by Django 5.0.1 on 2025-12-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_deprecated_place_and_location_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_range',
            field=models.CharField(blank=True, help_text='Target age: 0-5, 6-9, 10-12, 13-18, adults, all-ages', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='audience_tags',
            field=models.JSONField(blank=True, default=list, help_text='Audience categories: Children, Families, Teens, Seniors, etc.'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Event is cancelled'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_full',
            field=models.BooleanField(default=False, help_text='Registration full/waitlist'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Virtual/online event'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_registration',
            field=models.BooleanField(default=False, help_text='Registration required'),
        ),
        migrations.AddField(
            model_name='event',
            name='validation_score',
            field=models.FloatField(blank=True, help_text='LLM confidence in extraction (0.0-1.0)', null=True),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('referenced_events', models.ManyToManyField(blank=True, related_name='chat_references', to='events.event')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='events_chat_user_id_e0660c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='events_chat_user_id_fa361c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='events_chat_session_185422_idx'),
        ),
    ]
