# Generated by Django 5.0.1 on 2026-01-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_add_audience_and_chat_fields'),
        ('venues', '0008_venue_first_refactor_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_jobs', to='venues.venue'),
        ),
    ]
