# Generated by Django 5.0.1 on 2026-01-14 00:04

from django.db import migrations


def backfill_venue_events_urls(apps, schema_editor):
    """
    Migrate Source.base_url to Venue.events_urls for the venue-first architecture.

    For each Source with Events:
    1. Find the Venue(s) associated with those Events
    2. Add Source.base_url to Venue.events_urls if not already present

    Also update ScrapingJobs to link to Venue.
    """
    Source = apps.get_model('events', 'Source')
    Event = apps.get_model('events', 'Event')
    ScrapingJob = apps.get_model('events', 'ScrapingJob')
    Venue = apps.get_model('venues', 'Venue')

    # Track stats
    venues_updated = 0
    jobs_updated = 0

    for source in Source.objects.all():
        if not source.base_url:
            continue

        # Find all events from this source
        events = Event.objects.filter(source=source)
        if not events.exists():
            continue

        # Get unique venues from these events
        venue_ids = events.filter(venue__isnull=False).values_list('venue_id', flat=True).distinct()

        for venue_id in venue_ids:
            venue = Venue.objects.get(id=venue_id)
            current_urls = venue.events_urls or []

            # Add source URL if not already present
            if source.base_url not in current_urls:
                venue.events_urls = current_urls + [source.base_url]
                venue.save(update_fields=['events_urls'])
                venues_updated += 1

        # Update ScrapingJobs linked to this source to also link to venue
        # Use the first venue from events if available
        if venue_ids:
            first_venue_id = list(venue_ids)[0]
            updated = source.scraping_jobs.filter(venue__isnull=True).update(venue_id=first_venue_id)
            jobs_updated += updated

    print(f"Backfill complete: {venues_updated} venues updated, {jobs_updated} scraping jobs linked to venues")


def reverse_backfill(apps, schema_editor):
    """Reverse the migration by clearing events_urls."""
    Venue = apps.get_model('venues', 'Venue')
    ScrapingJob = apps.get_model('events', 'ScrapingJob')

    # Clear events_urls on all venues
    Venue.objects.update(events_urls=[])

    # Clear venue on all scraping jobs
    ScrapingJob.objects.update(venue=None)

    print("Reversed backfill: cleared events_urls and venue FKs")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_venue_first_refactor_phase1'),
        ('venues', '0008_venue_first_refactor_phase1'),
    ]

    operations = [
        migrations.RunPython(backfill_venue_events_urls, reverse_backfill),
    ]
