# Generated by Django 5.0.1 on 2026-01-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_backfill_venue_from_source'),
        ('venues', '0008_venue_first_refactor_phase1'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('venue', 'external_id')},
        ),
    ]
