# Generated by Django 5.0.1 on 2026-01-14 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def verify_no_null_venues(apps, schema_editor):
    """Verify all events have venues before making venue required."""
    Event = apps.get_model('events', 'Event')
    null_count = Event.objects.filter(venue__isnull=True).count()
    if null_count > 0:
        raise ValueError(f"Cannot make venue required: {null_count} events have no venue. Run backfill migration first.")
    print(f"Verified: all {Event.objects.count()} events have venues")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_change_event_unique_to_venue'),
        ('venues', '0008_venue_first_refactor_phase1'),
    ]

    operations = [
        # First verify no NULL venues exist
        migrations.RunPython(verify_no_null_venues, migrations.RunPython.noop),

        # Make source nullable (legacy field being phased out)
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.ForeignKey(
                blank=True,
                help_text='Legacy source reference (deprecated - use venue.events_urls)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='events',
                related_query_name='source_event',
                to='events.source',
            ),
        ),

        # Make venue required (no longer nullable)
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(
                help_text='Venue that hosts this event (required)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='venues.venue',
            ),
        ),
    ]
