# Generated by Django 5.0.1 on 2026-01-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_make_venue_required_source_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
        migrations.RemoveField(
            model_name='scrapingjob',
            name='source',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
