# Generated by Django 5.0.1 on 2026-01-17 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_source_model'),
        ('venues', '0010_add_nullable_to_osm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='error_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='triggered_by',
            field=models.CharField(blank=True, choices=[('periodic', 'Periodic Schedule'), ('manual', 'Manual/Admin'), ('admin_action', 'Admin Action'), ('retry_degraded', 'Retry Degraded'), ('service', 'Service API')], max_length=50),
        ),
        migrations.CreateModel(
            name='ScrapeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('domain', models.CharField(max_length=200)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('successful_attempts', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('total_events_found', models.PositiveIntegerField(default=0)),
                ('first_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('needs_attention', 'Needs Attention'), ('unscrapable', 'Unscrapable'), ('paused', 'Paused')], default='healthy', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('error_category', models.CharField(blank=True, max_length=50)),
                ('agent_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_histories', to='venues.venue')),
            ],
            options={
                'verbose_name_plural': 'Scrape histories',
            },
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='scrape_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='events.scrapehistory'),
        ),
        migrations.DeleteModel(
            name='ScrapeBatch',
        ),
        migrations.AddIndex(
            model_name='scrapehistory',
            index=models.Index(fields=['health_status'], name='events_scra_health__1833e1_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapehistory',
            index=models.Index(fields=['next_scheduled_at'], name='events_scra_next_sc_ddb9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapehistory',
            index=models.Index(fields=['domain'], name='events_scra_domain_edd8f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapehistory',
            unique_together={('venue', 'url')},
        ),
    ]
