# Generated by Django 5.0.1 on 2025-12-25 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDebugRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_text', models.TextField(help_text='The user query to test')),
                ('settings', models.JSONField(default=dict, help_text='Pipeline settings: model, temperature, max_events, location, radius, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('final_answer_text', models.TextField(blank=True, help_text='The LLM response')),
                ('total_latency_ms', models.IntegerField(blank=True, help_text='Total execution time in ms', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_stack', models.TextField(blank=True)),
                ('diagnostics', models.JSONField(blank=True, help_text='Analysis of what might be causing issues', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debug_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Debug Run',
                'verbose_name_plural': 'Chat Debug Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatDebugEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(help_text='Sequence number for ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('input', 'Input'), ('location_resolution', 'Location Resolution'), ('retrieval', 'Retrieval'), ('rerank', 'Rerank'), ('context_block', 'Context Block'), ('prompt_final', 'Final Prompt'), ('llm_request', 'LLM Request'), ('llm_chunk', 'LLM Chunk'), ('llm_response', 'LLM Response'), ('error', 'Error')], max_length=30)),
                ('data', models.JSONField(help_text='Full payload for this stage')),
                ('latency_ms', models.IntegerField(blank=True, help_text='Time taken for this stage', null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traces.chatdebugrun')),
            ],
            options={
                'verbose_name': 'Chat Debug Event',
                'verbose_name_plural': 'Chat Debug Events',
                'ordering': ['seq'],
            },
        ),
        migrations.AddIndex(
            model_name='chatdebugrun',
            index=models.Index(fields=['status'], name='traces_chat_status_b34bae_idx'),
        ),
        migrations.AddIndex(
            model_name='chatdebugrun',
            index=models.Index(fields=['created_at'], name='traces_chat_created_4ebb99_idx'),
        ),
        migrations.AddIndex(
            model_name='chatdebugrun',
            index=models.Index(fields=['created_by', '-created_at'], name='traces_chat_created_8574d5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatdebugevent',
            index=models.Index(fields=['run', 'seq'], name='traces_chat_run_id_d7f07d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatdebugevent',
            index=models.Index(fields=['stage'], name='traces_chat_stage_708fb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatdebugevent',
            constraint=models.UniqueConstraint(fields=('run', 'seq'), name='unique_run_seq'),
        ),
    ]
