# Generated by Django 5.0.1 on 2026-01-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdebugevent',
            name='error_severity',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatdebugevent',
            name='error_type',
            field=models.CharField(blank=True, choices=[('rag_error', 'RAG Error'), ('llm_error', 'LLM Error'), ('location_error', 'Location Error'), ('validation_error', 'Validation Error'), ('timeout_error', 'Timeout Error'), ('auth_error', 'Auth Error'), ('unknown', 'Unknown')], max_length=30, null=True),
        ),
    ]
