# Generated by Django 5.0.1 on 2025-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.CharField(help_text='Census GEOID (State FIPS + Place FIPS)', max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, help_text="Place name (e.g., 'Newton')", max_length=200)),
                ('normalized_name', models.CharField(db_index=True, help_text='Lowercase, cleaned name for matching', max_length=200)),
                ('state', models.CharField(db_index=True, help_text="USPS state abbreviation (e.g., 'MA')", max_length=2)),
                ('country_code', models.CharField(default='US', help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of internal point', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of internal point', max_digits=9)),
                ('lsad', models.CharField(blank=True, help_text='Legal/Statistical Area Descriptor (city, town, CDP)', max_length=20)),
                ('population', models.PositiveIntegerField(blank=True, help_text='Population for disambiguation ranking', null=True)),
                ('land_area_sqmi', models.DecimalField(blank=True, decimal_places=4, help_text='Land area in square miles', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'name'],
                'indexes': [models.Index(fields=['normalized_name', 'state'], name='locations_l_normali_a1c1fa_idx'), models.Index(fields=['normalized_name', 'country_code'], name='locations_l_normali_a510b1_idx'), models.Index(fields=['state', 'name'], name='locations_l_state_7b78de_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'state', 'country_code'), name='unique_location_by_state'),
        ),
    ]
