# Generated by Django 5.0.1 on 2025-12-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country_code', 'state', 'normalized_name'], name='locations_l_country_be1494_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['normalized_name', '-population'], name='locations_l_normali_7cd3bb_idx'),
        ),
    ]
