# Generated by Django 5.0.1 on 2025-12-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_add_suggest_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_by_state',
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'state', 'country_code', 'lsad'), name='unique_location_by_state_lsad'),
        ),
    ]
