# Generated by Django 5.0.1 on 2025-12-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_update_unique_constraint_include_lsad'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_by_state_lsad',
        ),
    ]
