# Generated by Django 5.0.1 on 2025-12-24 04:45

from django.db import migrations


def renormalize_locations(apps, schema_editor):
    """Re-normalize all location names to strip Census suffixes (CDP, city, town, etc.)."""
    import re

    Location = apps.get_model('locations', 'Location')

    def normalize_for_matching(name: str) -> str:
        if not name:
            return ""
        result = name.lower().strip()
        # Remove prefixes
        result = re.sub(r'^(city|town|village|borough|township)\s+of\s+', '', result)
        # Remove Census suffixes
        result = re.sub(r'\s+(city|town|village|cdp|borough|township|municipality)$', '', result)
        # Remove punctuation except hyphens
        result = re.sub(r'[^\w\s-]', '', result)
        # Collapse whitespace
        result = re.sub(r'\s+', ' ', result)
        return result.strip()

    # Update all locations
    locations = Location.objects.all()
    updated = 0
    for loc in locations:
        new_normalized = normalize_for_matching(loc.name)
        if loc.normalized_name != new_normalized:
            loc.normalized_name = new_normalized
            loc.save(update_fields=['normalized_name'])
            updated += 1

    print(f"Renormalized {updated} locations")


def reverse_renormalize(apps, schema_editor):
    """No-op reverse - we can't restore original normalization."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_name_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(renormalize_locations, reverse_renormalize),
    ]
